name: Deploy to IsardVDI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html || exit
            if [ ! -d ".git" ]; then
              git clone https://github.com/JustinPower0/practica-github-actionsRa3.git
            else
              git pull origin main
            fi
            sudo systemctl restart apache2

            